# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='quantity'),
            preserve_default=False,
        ),
    ]
