# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171215_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight_override',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
