# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=120)),
                ('cart_id', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=450)),
                ('delivery_time', models.CharField(max_length=122)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
    ]
