# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='address',
            field=models.CharField(max_length=450, verbose_name='Укажите свой адрес'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='comment',
            field=models.CharField(max_length=400, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='delivery_time',
            field=models.CharField(max_length=122, verbose_name='Желаемое время доставки'),
        ),
    ]
