# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171221_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='cart_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.Cart'),
        ),
    ]
