# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20171222_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='cart_id',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
